sudo: required
services:
  - docker
before_install:
  - docker build -t rakes4499/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true rakes4499/react-test npm test
after_success:
  - docker build -t rakes4499/multi-nginx ./nginx
  - docker build -t rakes4499/multi-worker ./worker
  - docker build -t rakes4499/multi-server ./server
  - docker build -t rakes4499/multi-client ./client
  # Log in the Docker hub
  - echo "$Docker_pass" | docker login -u "$Docker_username" --password-stdin
  # Take those images to Dockerhub
  - docker push rakes4499/multi-nginx
  - docker push	rakes4499/multi-worker
  - docker push	rakes4499/multi-server
  - docker push	rakes4499/multi-client
  - docker push	rakes4499/multi-nginx:v1
